[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "chromium", "chromedriver", "ffmpeg", "libGL", "mesa"]

[phases.install]
cmds = ["python3 -m venv /opt/venv", ". /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = "/opt/venv/bin/python -m uvicorn server:app --host 0.0.0.0 --port $PORT"
