nixPkgs = ["python311Full", "python311Packages.pip", "chromium", "chromedriver", "ffmpeg", "libGL", "mesa"]

[phases.install]
cmds = ["python -m pip install -r requirements.txt"]

[start]
cmd = "uvicorn server:app --host 0.0.0.0 --port $PORT"
