# Nixpacks configuration
# We rely on the standard Python provider for python setup (triggered by requirements.txt)
# We only need to add system dependencies here.

[phases.setup]
nixPkgs = ["chromium", "chromedriver", "ffmpeg", "libGL", "mesa"]
